name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        env:
          MY_ENV_VAR: ${{ secrets.MY_ENV_VAR }}
          ANOTHER_ENV_VAR: ${{ secrets.ANOTHER_ENV_VAR }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: 
        working-directory: ./path_to_project
        - name: Reference environment variable secrets
          run: |
            echo "MY_ENV_VAR is $MY_ENV_VAR"
            echo "ANOTHER_ENV_VAR is $ANOTHER_ENV_VAR "      
      - name: Run tests
        run: 
        working-directory: ./path_to_project
